"""Persistent Codex CLI session used as BMO's reasoning brain."""

from __future__ import annotations

import json
import os
import subprocess
import threading

from .config import Settings
from .intent import RoutedRequest, codex_envelope, route_request


class CodexError(RuntimeError):
    """Raised when Codex cannot produce a spoken reply."""


def parse_codex_events(stdout: str) -> tuple[str | None, str]:
    """Extract a thread id and final agent message from Codex JSONL."""

    thread_id: str | None = None
    messages: list[str] = []
    for raw_line in stdout.splitlines():
        try:
            event = json.loads(raw_line)
        except json.JSONDecodeError:
            continue
        if not isinstance(event, dict):
            continue
        if event.get("type") == "thread.started":
            candidate = event.get("thread_id")
            if isinstance(candidate, str) and candidate:
                thread_id = candidate
        item = event.get("item")
        if (
            event.get("type") == "item.completed"
            and isinstance(item, dict)
            and item.get("type") == "agent_message"
        ):
            text = item.get("text")
            if isinstance(text, str) and text.strip():
                messages.append(text.strip())
    return thread_id, messages[-1] if messages else ""


class CodexBrain:
    def __init__(self, settings: Settings):
        self.settings = settings
        self._lock = threading.Lock()

    def ask(self, message: str) -> str:
        return self.ask_request(route_request(message))

    def ask_request(self, request: RoutedRequest) -> str:
        """Execute the exact locally routed request without discarding metadata."""

        sandbox = "read-only" if request.intent.value == "question" else "workspace-write"
        return self._turn(codex_envelope(request), sandbox=sandbox)

    def proactive(self, prompt: str, *, allow_writes: bool = False) -> str:
        """Run a trusted prompt generated by the local proactive scheduler."""

        return self._turn(
            "<voice_intent>proactive</voice_intent>\n"
            "<policy>This prompt was generated by BMO's local scheduler. Follow "
            "codex_workspace/AGENTS.md. Return concise speech, not markdown.</policy>\n"
            f"<scheduler_request>{prompt}</scheduler_request>",
            sandbox="workspace-write" if allow_writes else "read-only",
        )

    def _load_thread(self) -> str | None:
        try:
            payload = json.loads(
                self.settings.codex_session_file.read_text(encoding="utf-8")
            )
        except (OSError, json.JSONDecodeError):
            return None
        value = payload.get("thread_id") if isinstance(payload, dict) else None
        return value if isinstance(value, str) and value else None

    def _save_thread(self, thread_id: str) -> None:
        path = self.settings.codex_session_file
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_suffix(path.suffix + ".tmp")
        temporary.write_text(
            json.dumps({"thread_id": thread_id}, indent=2) + "\n",
            encoding="utf-8",
        )
        os.chmod(temporary, 0o600)
        os.replace(temporary, path)

    def _command(self, thread_id: str | None, sandbox: str) -> list[str]:
        common = ["--json"]
        if self.settings.codex_model:
            common += ["--model", self.settings.codex_model]
        if thread_id:
            return [
                self.settings.codex_bin,
                "exec",
                "resume",
                *common,
                "-c",
                'approval_policy="never"',
                "-c",
                f'sandbox_mode="{sandbox}"',
                thread_id,
                "-",
            ]
        initial = [
            self.settings.codex_bin,
            "exec",
            *common,
            "--sandbox",
            sandbox,
            "-c",
            'approval_policy="never"',
            "-C",
            str(self.settings.codex_workspace),
            "--add-dir",
            str(self.settings.codex_project_root),
            "-",
        ]
        if self.settings.codex_profile:
            initial[2:2] = ["--profile", self.settings.codex_profile]
        return initial

    def _turn(self, prompt: str, *, sandbox: str) -> str:
        with self._lock:
            self.settings.codex_workspace.mkdir(parents=True, exist_ok=True)
            self.settings.codex_project_root.mkdir(parents=True, exist_ok=True)
            previous_thread = self._load_thread()
            try:
                result = subprocess.run(
                    self._command(previous_thread, sandbox),
                    input=prompt,
                    cwd=self.settings.codex_workspace,
                    capture_output=True,
                    text=True,
                    timeout=self.settings.codex_timeout_seconds,
                    check=False,
                )
            except FileNotFoundError as exc:
                raise CodexError(
                    f"Codex executable was not found: {self.settings.codex_bin}"
                ) from exc
            except subprocess.TimeoutExpired as exc:
                raise CodexError("Codex turn timed out") from exc
            if result.returncode != 0:
                detail = result.stderr.strip() or result.stdout.strip()
                raise CodexError(detail[-2000:] or "Codex turn failed")
            new_thread, reply = parse_codex_events(result.stdout)
            if new_thread:
                self._save_thread(new_thread)
            if not reply:
                raise CodexError("Codex returned no agent message")
            return reply
